sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: DMO9x5t9BqyPpMxs8JYzEpj/EeCznx+ToMUBf7pyoKFuOsyKhdWfiGhN74ZlmTUR+H31OwbPPC68aczIz0R4r56mFKX6bgTspxj9LYOE/uIiNIeuevtUpAC3ZCfKHEGR8doaA99exQVvcUfqB76hZM+zrzoT0sZlg741Dsc+D/mw5Som1X/nCnTe/GmRMabSXCBE/+i9Q05al7FaBn1ptbxtCg6c4AGhSqNUOPtTcfCDIuRQ58R48ltCyLOAPkDOZFXloXFn/4L1oZBNXBkBQr9s3DGkbFKZyWbM79DHXbyd4dsUVy8+gUcM/hU3JaOLsVpTohxh8nmZjbmYZKJD5G8WpS+Bf2cTEBqhqUtPbGW2G0RYCynI7lqA2Hhc7jXbUZK7VIrAa4KAwDuEm0+7pvhAfRnj5Lrjtc0ivF0+R3CzCxHskcftW5v9DsEUrZumcbJn8FgtNIim3ZmHeyrPJEAQMC4qW1KNtu/1TwgPexIzkSf9Ss9wv2nIm8bqLutSz1VX6BayjsOk8FvCcleaqARCeOu5n9EuORECytwiS62VGWjzbSF7ml2RXpBRZPOF6Cuc2dnSoSnou7+mdv1uudzV5yFYjZpbJs0EcIz3PMYNiAQ3NiFJhtHilDHVKbM+rn7kR4Bx9ZgX/09Onup74OV+iGGNSDy7N+rweyYdh0U=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-King-of-the-Golden-River_701
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy